### ISSUE TITLE
Looks like plugin generate false CRITICAL result when check command return empty list

### ISSUE THREAD

**Issue by IvanBayan** [CaptPhunkosis/check_rabbitmq#5]
root@host:/usr/local/lib/nagios/plugins# ./check_rabbitmq -a queues_count -C 100 -W 80
CRITICAL - list index out of range
root@host:/usr/local/lib/nagios/plugins#  rabbitmqctl list_queues
Listing queues ...
root@host:/usr/local/lib/nagios/plugins# echo $?
0

**Comment by CaptPhunkosis** [comment]
Hey @IvanBayan,

It's been four years since I've even used rabbitmq so I wouldn't be shocked to find if this doesn't even work with current versions of the service.  If you want to toss a pull request with a fix my way I'm more than happy to merge it in.  Probably won't be fixing this myself though.

Thanks
